# Note: Tensorflow support is for Apple Silicon
name: comp90042_project
channels:
  - conda-forge
  - apple
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - notebook
  - ipykernel
  - tqdm
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - gensim
  - spacy
  - apple::tensorflow-deps==2.9 # Tensorflow Apple Silicon MacOS 12.1+
  - pytorch
  - torchvision
  - torchaudio
  - sentence-transformers # Hugging Face Apple Silicon
  - pip
  - pip:
    - tensorflow-macos==2.9 # Tensorflow Apple Silicon MacOS 12.1+
    - tensorflow-metal==0.5.0 # Tensorflow Apple Silicon MacOS 12.1+
    - torcheval